import { chromium } from "playwright";
const base = "http://localhost:3119";
const out = process.argv[2];
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const page = await browser.newPage({ viewport: { width: 1280, height: 1000 } });
await page.goto(`${base}/signup`);
await page.getByLabel("Full name").fill("Shot Owner");
await page.getByLabel("Email").fill(`shot-${Date.now()}@trnd.dev`);
await page.getByLabel("Password").fill("trnd-e2e-password");
await page.getByRole("button", { name: "Create account" }).click();
await page.waitForURL(/\/onboarding/);
await page.getByLabel("Business name").fill("Glow Aesthetics Studio");
await page.getByRole("button", { name: "Continue" }).click();
await page.getByRole("button", { name: "Health & beauty" }).click();
await page.getByRole("button", { name: "Continue" }).click();
await page.getByLabel("City").fill("Atlanta");
await page.getByLabel("State / region").fill("GA");
await page.getByRole("button", { name: "Continue" }).click();
await page.getByLabel("Service 1 name").fill("Facial balancing consult");
await page.getByLabel("Service 1 price").fill("$99");
await page.getByRole("button", { name: "Continue" }).click();
await page.getByLabel("Brand voice notes").fill("Warm but direct.");
const toApp = page.waitForURL(/\/app$/, { timeout: 30000 });
await page.getByRole("button", { name: /Finish setup|Finishing setup/ }).click({ timeout: 10000 }).catch(() => {});
await toApp;
await page.getByRole("link", { name: "Open the campaign" }).waitFor({ timeout: 60000 });
await page.waitForTimeout(500);
await page.screenshot({ path: `${out}/d3-0.png` });
await page.evaluate(() => window.scrollTo(0, 1000)); await page.waitForTimeout(400);
await page.screenshot({ path: `${out}/d3-1.png` });
await page.locator("details.howto summary").first().click(); await page.waitForTimeout(400);
await page.evaluate(() => window.scrollTo(0, 500)); await page.waitForTimeout(400);
await page.screenshot({ path: `${out}/d3-why.png` });
const href = await page.getByRole("link", { name: "Open the campaign" }).getAttribute("href");
await page.goto(`${base}${href}`); await page.waitForTimeout(500);
await page.screenshot({ path: `${out}/c3-0.png` });
await page.goto(`${base}/app/settings`); await page.waitForTimeout(500);
await page.screenshot({ path: `${out}/s3-0.png` });
await browser.close();
