import Link from "next/link";
import { notFound, redirect } from "next/navigation";

import AdPreview from "@/components/app/ad-preview";
import CopyAllButton from "@/components/app/copy-all-button";
import CopyBlock from "@/components/app/copy-block";
import SourceBadge from "@/components/app/source-badge";
import StatusTimeline from "@/components/app/status-timeline";
import { getSessionUser } from "@/lib/auth/session";
import { markLaunchedAction } from "@/lib/campaigns/actions";
import { budgetFor } from "@/lib/recommend/insights";
import { getUserRepo } from "@/lib/db";
import type { Creative } from "@/lib/db/types";

export const metadata = { title: "Campaign — TRND" };

const KIND_LABELS: Record<Creative["kind"], string> = {
  headline: "Headline",
  primary_text: "Primary text",
  script: "Video script",
  static_brief: "Static brief",
  landing_copy: "Landing copy",
};

export default async function CampaignPage({ params }: PageProps<"/app/campaigns/[id]">) {
  const { id } = await params;
  const user = await getSessionUser();
  if (!user) redirect("/login");
  const repo = await getUserRepo(user.id);
  const campaign = await repo.getCampaign(id);
  if (!campaign) notFound();
  const [creatives, opportunity, business] = await Promise.all([
    repo.listCreatives(id),
    repo.getOpportunity(campaign.opportunity_id),
    repo.getBusiness(campaign.business_id),
  ]);
  const signal = opportunity ? await repo.getSignal(opportunity.signal_id) : null;

  const byKind = (kind: Creative["kind"]) => creatives.filter((c) => c.kind === kind);
  const headlines = byKind("headline");
  const primaries = byKind("primary_text");
  const budget = budgetFor(business?.price_band ?? null);

  const copyAll = [
    `ANGLE\n${campaign.angle}`,
    `HOOK\n${campaign.hook}`,
    `OFFER\n${campaign.offer}`,
    `AUDIENCE\n${campaign.audience.who} · ${campaign.audience.age_range} · ${campaign.audience.radius_miles}mi\nWhy: ${campaign.audience.why}`,
    ...(["headline", "primary_text", "script", "static_brief", "landing_copy"] as const).map(
      (kind) =>
        `${KIND_LABELS[kind].toUpperCase()}S\n` +
        byKind(kind)
          .map((c, i) => `${i + 1}. ${c.content}`)
          .join("\n\n"),
    ),
  ].join("\n\n———\n\n");

  const launched = campaign.status === "live" || campaign.status === "complete";

  return (
    <div className="page">
      <Link href="/app" className="mono-label" style={{ display: "inline-block", marginBottom: 16 }}>
        ← This week
      </Link>

      {/* ---------- HEADER ---------- */}
      <header className="panel panel--hero" style={{ padding: "30px 32px" }}>
        <div style={{ display: "flex", justifyContent: "space-between", gap: 20, flexWrap: "wrap", alignItems: "flex-start" }}>
          <div style={{ maxWidth: 620 }}>
            <div style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap", marginBottom: 12 }}>
              <span className="badge badge--amber"><i />finished campaign</span>
              {signal && <SourceBadge source={signal.source} />}
              <span className="badge"><i />{campaign.channel} · paid social</span>
            </div>
            <h1 className="h-disp" style={{ fontSize: "clamp(24px,3vw,34px)", margin: "0 0 12px", lineHeight: 1.12 }}>
              {campaign.hook}
            </h1>
            <p style={{ fontSize: 15, lineHeight: 1.65, color: "var(--ink-soft)", margin: 0 }}>{campaign.angle}</p>
          </div>
          <StatusTimeline status={campaign.status} />
        </div>

        <div className="facts-grid" style={{ marginTop: 24, paddingTop: 20, borderTop: "1px dashed var(--line)" }}>
          <div>
            <span className="k" style={{ color: "var(--amber-text)" }}>Offer</span>
            <p className="v" style={{ fontWeight: 600, fontFamily: "var(--disp)" }}>{campaign.offer}</p>
          </div>
          <div>
            <span className="k">Audience</span>
            <p className="v" style={{ fontSize: 13.5 }}>
              {campaign.audience.who} · {campaign.audience.age_range} · {campaign.audience.radius_miles} mi
            </p>
          </div>
          <div>
            <span className="k">Source signal</span>
            <p className="v" style={{ fontSize: 13.5 }}>{signal ? `"${signal.term}"` : "—"}</p>
          </div>
          <div>
            <span className="k">Generated by</span>
            <p className="v" style={{ fontSize: 12.5, fontFamily: "var(--mono)" }} title={`prompt ${campaign.prompt_version}`}>
              {campaign.model_used} · {campaign.prompt_version}
            </p>
          </div>
        </div>

        <div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginTop: 24 }}>
          {!launched ? (
            <form action={markLaunchedAction}>
              <input type="hidden" name="campaign_id" value={campaign.id} />
              <button type="submit" className="btn btn-primary btn-sm">
                Mark as launched
              </button>
            </form>
          ) : (
            <Link href="/app/results" className="btn btn-primary btn-sm">
              Enter results →
            </Link>
          )}
          <CopyAllButton text={copyAll} />
          <a className="btn btn-ghost btn-sm" href={`/app/campaigns/${campaign.id}/export?format=json`}>
            Download JSON
          </a>
          <a className="btn btn-ghost btn-sm" href={`/app/campaigns/${campaign.id}/export?format=csv`}>
            CSV for Meta
          </a>
        </div>
      </header>

      {/* ---------- PREVIEW + LAUNCH PLAN ---------- */}
      <div className="two-col" style={{ display: "grid", gridTemplateColumns: "1fr 1.35fr", gap: 18, marginTop: 18, alignItems: "start" }}>
        <section className="panel">
          <div className="panel__head">
            <span className="panel__title">How it reads in-feed</span>
          </div>
          <AdPreview
            businessName={business?.name ?? "Your business"}
            primaryText={primaries[0]?.content ?? campaign.angle}
            headline={headlines[0]?.content ?? campaign.hook}
            mediaLine={campaign.offer}
          />
        </section>

        <section className="panel">
          <div className="panel__head">
            <span className="panel__title">Launch plan</span>
            <span className="panel__meta">suggestions — you stay in control</span>
          </div>
          <div className="facts-grid" style={{ marginBottom: 20 }}>
            <div>
              <span className="k">Suggested daily budget</span>
              <p className="v" style={{ fontFamily: "var(--disp)", fontWeight: 700, fontSize: 20 }}>
                {budget.daily}
                <small style={{ fontFamily: "var(--mono)", fontSize: 10.5, fontWeight: 500, color: "var(--ink-faint)", marginLeft: 6 }}>/ day</small>
              </p>
              <p style={{ fontSize: 12, color: "var(--ink-faint)", margin: "4px 0 0" }}>
                sized to your {business?.price_band ?? "$$"} price band
              </p>
            </div>
            <div>
              <span className="k">Test flight</span>
              <p className="v" style={{ fontFamily: "var(--disp)", fontWeight: 700, fontSize: 20 }}>{budget.test}</p>
              <p style={{ fontSize: 12, color: "var(--ink-faint)", margin: "4px 0 0" }}>
                enough spend to read a winner
              </p>
            </div>
          </div>

          <div className="panel__head" style={{ marginTop: 4 }}>
            <span className="panel__title">Test flight plan</span>
          </div>
          <div className="flight" style={{ marginBottom: 18 }}>
            <div className="flight__step">
              <span className="flight__when">Days 1–3</span>
              <p className="flight__what">
                <b>Headline 1 vs headline 2</b>, both on primary text 1, even spend.
              </p>
            </div>
            <div className="flight__step">
              <span className="flight__when">Days 4–6</span>
              <p className="flight__what">
                <b>Keep the winner</b>, swap in primary text 2 against it.
              </p>
            </div>
            <div className="flight__step">
              <span className="flight__when">Kill rule</span>
              <p className="flight__what">
                Pause anything under <b>half your median CTR</b> after 1,000 impressions.
              </p>
            </div>
          </div>

          <div className="panel__head">
            <span className="panel__title">Launch checklist</span>
          </div>
          <div className="checklist">
            {[
              "Copy the assets below into Meta Ads Manager (or export the CSV).",
              `Set the audience: ${campaign.audience.who}, ${campaign.audience.age_range}, ${campaign.audience.radius_miles} mile radius.`,
              `Set ${budget.daily}/day and schedule the ${budget.test.split(" over ")[1]} test flight.`,
              "Mark as launched here, then record results after the flight — that's what sharpens next week.",
            ].map((t, i) => (
              <div key={i}>
                <svg width="15" height="15" viewBox="0 0 16 16" aria-hidden="true">
                  <path d="M3 8.5L6.5 12L13 4" stroke="var(--amber)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" fill="none" />
                </svg>
                {t}
              </div>
            ))}
          </div>
        </section>
      </div>

      {/* ---------- CREATIVE ASSETS ---------- */}
      <section style={{ marginTop: 30 }}>
        <div className="panel__head" style={{ marginBottom: 12 }}>
          <span className="panel__title">Headlines</span>
          <span className="panel__meta">{headlines.length} variants</span>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: 12 }}>
          {headlines.map((c) => (
            <CopyBlock key={c.id} label={`Headline ${c.variant_index + 1}`} content={c.content} />
          ))}
        </div>
      </section>

      <section style={{ marginTop: 28 }}>
        <div className="panel__head" style={{ marginBottom: 12 }}>
          <span className="panel__title">Primary texts</span>
          <span className="panel__meta">{primaries.length} variants</span>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))", gap: 12 }}>
          {primaries.map((c) => (
            <CopyBlock key={c.id} label={`Primary text ${c.variant_index + 1}`} content={c.content} />
          ))}
        </div>
      </section>

      <details className="section-disclosure" style={{ marginTop: 18 }}>
        <summary>
          <span className="panel__title">Short-form video scripts</span>
          <span className="summary-right">
            <span className="panel__meta">{byKind("script").length} scripts · 20–30s each</span>
            <span className="summary-open-hint">open ↓</span>
          </span>
        </summary>
        <div className="section-body">
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(340px, 1fr))", gap: 12 }}>
            {byKind("script").map((c) => (
              <CopyBlock key={c.id} label={`Script ${c.variant_index + 1}`} content={c.content} mono />
            ))}
          </div>
        </div>
      </details>

      <details className="section-disclosure" style={{ marginTop: 18 }}>
        <summary>
          <span className="panel__title">Static creative briefs</span>
          <span className="summary-right">
            <span className="panel__meta">hand to any designer — or shoot on a phone</span>
            <span className="summary-open-hint">open ↓</span>
          </span>
        </summary>
        <div className="section-body">
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))", gap: 12 }}>
            {byKind("static_brief").map((c) => (
              <CopyBlock key={c.id} label={`Static ${c.variant_index + 1}`} content={c.content} />
            ))}
          </div>
        </div>
      </details>

      <details className="section-disclosure" style={{ marginTop: 18 }}>
        <summary>
          <span className="panel__title">Landing copy</span>
          <span className="summary-right">
            <span className="panel__meta">for the page the ad points at</span>
            <span className="summary-open-hint">open ↓</span>
          </span>
        </summary>
        <div className="section-body">
          <div style={{ maxWidth: 720 }}>
            {byKind("landing_copy").map((c) => (
              <CopyBlock key={c.id} label="Landing section" content={c.content} />
            ))}
          </div>
        </div>
      </details>

      <p style={{ marginTop: 32, fontSize: 13, lineHeight: 1.6, color: "var(--ink-soft)", maxWidth: 640 }}>
        <span className="mono-label" style={{ color: "var(--amber-text)" }}>Why this audience: </span>
        {campaign.audience.why}
      </p>
    </div>
  );
}
