import Link from "next/link";
import { notFound, redirect } from "next/navigation";

import CopyAllButton from "@/components/app/copy-all-button";
import CopyBlock from "@/components/app/copy-block";
import { getSessionUser } from "@/lib/auth/session";
import { markLaunchedAction } from "@/lib/campaigns/actions";
import { getUserRepo } from "@/lib/db";
import type { Creative } from "@/lib/db/types";

export const metadata = { title: "Campaign — TRND" };

const KIND_LABELS: Record<Creative["kind"], string> = {
  headline: "Headline",
  primary_text: "Primary text",
  script: "Video script",
  static_brief: "Static brief",
  landing_copy: "Landing copy",
};

const STATUS_COLOR: Record<string, string> = {
  draft: "var(--ink-faint)",
  exported: "var(--amber)",
  live: "var(--mint)",
  complete: "var(--mint)",
};

export default async function CampaignPage({ params }: PageProps<"/app/campaigns/[id]">) {
  const { id } = await params;
  const user = await getSessionUser();
  if (!user) redirect("/login");
  const repo = await getUserRepo(user.id);
  const campaign = await repo.getCampaign(id);
  if (!campaign) notFound();
  const [creatives, opportunity] = await Promise.all([
    repo.listCreatives(id),
    repo.getOpportunity(campaign.opportunity_id),
  ]);
  const signal = opportunity ? await repo.getSignal(opportunity.signal_id) : null;

  const byKind = (kind: Creative["kind"]) => creatives.filter((c) => c.kind === kind);
  const copyAll = [
    `ANGLE\n${campaign.angle}`,
    `HOOK\n${campaign.hook}`,
    `OFFER\n${campaign.offer}`,
    `AUDIENCE\n${campaign.audience.who} · ${campaign.audience.age_range} · ${campaign.audience.radius_miles}mi\nWhy: ${campaign.audience.why}`,
    ...(["headline", "primary_text", "script", "static_brief", "landing_copy"] as const).map(
      (kind) =>
        `${KIND_LABELS[kind].toUpperCase()}S\n` +
        byKind(kind)
          .map((c, i) => `${i + 1}. ${c.content}`)
          .join("\n\n"),
    ),
  ].join("\n\n———\n\n");

  return (
    <div className="wrap" style={{ padding: "44px 32px 80px" }}>
      <Link href="/app" className="mono-label" style={{ display: "inline-block", marginBottom: 18 }}>
        ← This week
      </Link>

      <header className="card-lg" style={{ padding: "32px 34px", borderColor: "var(--amber)", background: "linear-gradient(180deg, var(--amber-soft), transparent 60%)" }}>
        <div style={{ display: "flex", justifyContent: "space-between", gap: 16, flexWrap: "wrap", alignItems: "flex-start" }}>
          <div style={{ maxWidth: 640 }}>
            <span className="eyebrow" style={{ marginBottom: 12 }}>
              Finished campaign{signal ? ` — from "${signal.term}"` : ""}
            </span>
            <h1 className="h-disp" style={{ fontSize: "clamp(24px,3vw,34px)", margin: "0 0 12px", lineHeight: 1.15 }}>
              {campaign.hook}
            </h1>
            <p style={{ fontSize: 15, lineHeight: 1.65, color: "var(--ink-soft)", margin: 0 }}>{campaign.angle}</p>
          </div>
          <span
            className="mono-label"
            style={{ border: `1px solid ${STATUS_COLOR[campaign.status]}`, color: STATUS_COLOR[campaign.status], borderRadius: 999, padding: "6px 14px" }}
          >
            {campaign.status}
          </span>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 14, marginTop: 24, paddingTop: 20, borderTop: "1px dashed var(--line)" }}>
          <div>
            <span className="mono-label" style={{ color: "var(--amber)" }}>Offer</span>
            <p style={{ margin: "5px 0 0", fontSize: 14.5, fontWeight: 600, fontFamily: "var(--disp)" }}>{campaign.offer}</p>
          </div>
          <div>
            <span className="mono-label">Audience</span>
            <p style={{ margin: "5px 0 0", fontSize: 13.5, lineHeight: 1.5 }}>
              {campaign.audience.who} · {campaign.audience.age_range} · {campaign.audience.radius_miles} mi
            </p>
          </div>
          <div>
            <span className="mono-label">Channel</span>
            <p style={{ margin: "5px 0 0", fontSize: 13.5 }}>{campaign.channel} (paid social)</p>
          </div>
          <div>
            <span className="mono-label">Generated by</span>
            <p style={{ margin: "5px 0 0", fontSize: 12.5, fontFamily: "var(--mono)" }} title={`prompt ${campaign.prompt_version}`}>
              {campaign.model_used}
            </p>
          </div>
        </div>

        <div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginTop: 24 }}>
          {campaign.status !== "live" && campaign.status !== "complete" ? (
            <form action={markLaunchedAction}>
              <input type="hidden" name="campaign_id" value={campaign.id} />
              <button type="submit" className="btn btn-primary btn-sm">
                Mark as launched
              </button>
            </form>
          ) : (
            <Link href="/app/results" className="btn btn-primary btn-sm">
              Enter results →
            </Link>
          )}
          <CopyAllButton text={copyAll} />
          <a className="btn btn-ghost btn-sm" href={`/app/campaigns/${campaign.id}/export?format=json`}>
            Download JSON
          </a>
          <a className="btn btn-ghost btn-sm" href={`/app/campaigns/${campaign.id}/export?format=csv`}>
            CSV for Meta
          </a>
        </div>
      </header>

      <section style={{ marginTop: 40 }}>
        <h2 className="mono-label" style={{ marginBottom: 14 }}>Headlines — 5 variants</h2>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: 12 }}>
          {byKind("headline").map((c) => (
            <CopyBlock key={c.id} label={`Headline ${c.variant_index + 1}`} content={c.content} />
          ))}
        </div>
      </section>

      <section style={{ marginTop: 34 }}>
        <h2 className="mono-label" style={{ marginBottom: 14 }}>Primary texts — 3 variants</h2>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))", gap: 12 }}>
          {byKind("primary_text").map((c) => (
            <CopyBlock key={c.id} label={`Primary text ${c.variant_index + 1}`} content={c.content} />
          ))}
        </div>
      </section>

      <section style={{ marginTop: 34 }}>
        <h2 className="mono-label" style={{ marginBottom: 14 }}>Short-form video scripts — 3</h2>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(340px, 1fr))", gap: 12 }}>
          {byKind("script").map((c) => (
            <CopyBlock key={c.id} label={`Script ${c.variant_index + 1}`} content={c.content} mono />
          ))}
        </div>
      </section>

      <section style={{ marginTop: 34 }}>
        <h2 className="mono-label" style={{ marginBottom: 14 }}>Static creative briefs — 3</h2>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))", gap: 12 }}>
          {byKind("static_brief").map((c) => (
            <CopyBlock key={c.id} label={`Static ${c.variant_index + 1}`} content={c.content} />
          ))}
        </div>
      </section>

      <section style={{ marginTop: 34, maxWidth: 720 }}>
        <h2 className="mono-label" style={{ marginBottom: 14 }}>Landing copy</h2>
        {byKind("landing_copy").map((c) => (
          <CopyBlock key={c.id} label="Landing section" content={c.content} />
        ))}
      </section>

      <p className="mono-label" style={{ marginTop: 36 }}>
        Audience rationale: {campaign.audience.why}
      </p>
    </div>
  );
}
