import type { Business, NewBusinessBrief, Service } from "@/lib/db/types";
import { isGeminiConfigured } from "@/lib/env";
import { CATEGORY_CONFIGS } from "@/lib/signals/category-terms";

export const BRIEF_FALLBACK_MODEL = "trnd-template/v3";
export const BRIEF_PROMPT_VERSION = "brief-5";

/**
 * The full analysis a business gets when it joins: positioning, who buys,
 * the local market, a pricing read, seasonality, strengths, moat, edges,
 * watchouts, and concrete first moves. Deterministic template here; Gemini
 * (Pro) takes over when the key is present. Briefs whose prompt_version
 * predates BRIEF_PROMPT_VERSION are regenerated by the app.
 */

const WATCHOUTS: Record<string, string[]> = {
  "Health & beauty": [
    "No before/after promises or medical claims — ad platforms reject them and they invite scrutiny.",
    "Don't compete on discounts; sell judgment, safety, and taste. Cheap looks risky in this category.",
  ],
  "Dental & wellness": [
    "Health claims and guarantees get ads rejected — sell comfort, clarity, and convenience instead.",
    "Avoid fear-based messaging; it converts poorly and erodes trust in a provider relationship.",
  ],
  "Restaurants & cafés": [
    "Avoid a discount-led identity — it fills seats once with deal hunters, not regulars.",
    "Never advertise an item you can't deliver consistently at rush; one bad first visit undoes the ad.",
  ],
  "Home services": [
    "Don't lead with 'cheapest' — those leads price-shop every job. Sell speed and reliability.",
    "Don't promise arrival windows the schedule can't keep; missed windows become public reviews.",
  ],
  "Fitness studios": [
    "Body-transformation claims are restricted on ad platforms — sell energy, community, and consistency.",
    "Don't market intensity to beginners; it reads as a barrier, not a benefit.",
  ],
  "Retail & boutiques": [
    "Constant sale messaging trains your audience to wait for the next one — protect full price.",
    "Avoid generic product shots; your edit and your point of view are the reason to buy here.",
  ],
  "Auto services": [
    "Avoid scare tactics about safety; convenience and honesty convert better and hold trust.",
    "Don't quote prices in ads you can't honor on arrival — bait pricing kills local reputation.",
  ],
};

const MOATS: Record<string, string> = {
  "Health & beauty":
    "Trust compounds here: results people can see, practitioners they come back to. A national brand can't replicate a face someone already trusts.",
  "Dental & wellness":
    "Patients switch providers rarely — winning the first visit wins years of visits. Local trust is the whole game.",
  "Restaurants & cafés":
    "You're a habit, not a transaction. Being someone's default spot in a 20-minute radius is a position no delivery app can take.",
  "Home services":
    "Showing up on time, twice, makes you the contact in someone's phone. That saved contact is the moat.",
  "Fitness studios":
    "Community is the retention engine — people stay for the people. That can't be copied by a cheaper gym.",
  "Retail & boutiques":
    "Your curation is the product. An algorithm can list items; it can't have taste people identify with.",
  "Auto services":
    "Car trouble is a trust purchase. The shop people recommend by name owns the neighborhood.",
};

const PRICE_ADVANTAGE: Record<string, string> = {
  "$": "Accessible pricing is an honest hook — lead with the real number; it beats vague 'affordable' claims.",
  "$$": "Mid-market sweet spot: premium feel without premium anchor pricing — name the price in the ad with confidence.",
  "$$$": "Premium price is a filter, not a barrier — say it plainly and sell the standard behind it.",
};

const SEGMENTS: Record<string, string[]> = {
  "Restaurants & cafés": [
    "Nearby regulars building a habit — they choose on consistency and how the place feels, against the two other spots on their route.",
    "Occasion-driven visitors (dates, catch-ups, weekend plans) who pick from search and social — photos and one signature item decide it.",
    "Remote workers and daytime lingerers who buy time and atmosphere as much as the order itself.",
  ],
  "Home services": [
    "Emergency callers who choose whoever answers first and can come today — speed wins before price is even discussed.",
    "Planned-project homeowners comparing two or three quotes — proof of reliability and clear scope beat the lowest bid.",
    "Repeat and referral customers whose only comparison is 'the one we used last time' — staying saved in their phone is the sale.",
  ],
  "Health & beauty": [
    "Loyal clients on a maintenance cycle — they buy the practitioner, not the treatment, and rebook on trust.",
    "First-timers researching a specific treatment — they compare credentials and reviews and are nervous about a bad result.",
    "Event-driven bookings (weddings, reunions, seasons) with a hard deadline and a willingness to pay for certainty.",
  ],
  "Fitness studios": [
    "Beginners looking for a low-pressure way in — they compare vibes and fear of embarrassment more than equipment lists.",
    "Committed regulars shopping for schedule fit and community — they leave when classes fill or friendships don't form.",
    "Goal-driven joiners (new year, summer, an event) who convert fast on a clear intro offer and churn without early wins.",
  ],
  "Retail & boutiques": [
    "Taste-driven browsers who follow the shop's point of view — new arrivals and the owner's edit are the draw.",
    "Gift buyers with a deadline and a budget — they need confidence they can walk in and solve it in fifteen minutes.",
    "Destination shoppers who found you online and want what the big stores don't carry.",
  ],
  "Auto services": [
    "Breakdown and warning-light customers who need it handled now — trust and same-week availability decide it.",
    "Maintenance-cycle drivers comparing you to the dealership on price and to the quick-lube on honesty.",
    "Households standardizing on one shop for every car — win one visit well and the whole driveway follows.",
  ],
  "Dental & wellness": [
    "Families choosing a long-term provider — insurance fit, gentleness, and scheduling ease decide it.",
    "Cosmetic-intent patients (whitening, aligners, veneers) who research for weeks and convert on credibility.",
    "Lapsed patients who know they're overdue — a judgment-free re-entry offer is what moves them.",
  ],
};

const MARKET_CONTEXT: Record<string, string> = {
  "Restaurants & cafés":
    "Local food is a frequency market: people rotate a short list of defaults, and the fight is to get on that list. Your real competition includes delivery apps and the grocery store, not just other restaurants. Discovery happens on maps, search, and social photos — the businesses that show up when someone nearby is hungry win a disproportionate share.",
  "Home services":
    "Demand is intent-driven and urgent: nobody browses for a plumber. The market splits into emergency jobs won by responsiveness and planned projects won by trust signals — reviews, photos of real work, clear pricing. National lead-gen platforms sell the same homeowner to five contractors; owning your own local presence means not paying rent on every lead.",
  "Health & beauty":
    "This is a trust-and-results market with high lifetime value: one converted client can be years of rebookings. Competition includes both other local providers and the do-nothing option — most prospects delay for months. Credibility (reviews, credentials, consistent aesthetic) converts better than discounts, and word of mouth is amplified, not replaced, by ads.",
  "Fitness studios":
    "Fitness is a churn business dressed as a membership business: the market constantly refills with people restarting. You compete with big-box gyms on price, boutique rivals on vibe, and home workouts on convenience — so the sell is community and accountability, the two things the alternatives can't fake. Intro offers do the recruiting; the first two weeks do the retaining.",
  "Retail & boutiques":
    "Independent retail wins on curation and story against effectively infinite online supply. Foot traffic follows the neighborhood's rhythm, but the growth lever is becoming a destination — people who saw a specific item or the shop's point of view online and came in for it. Every ad should look like your shelf, not like a catalog.",
  "Auto services":
    "Car repair is a low-trust category, which is the opportunity: the shop that communicates plainly and honors its quotes stands out immediately. You compete with dealerships on price and chains on credibility. Almost every customer starts at search with urgent intent, and reviews function as the de facto pricing page — volume and recency matter more than perfection.",
  "Dental & wellness":
    "Providers are chosen rarely and kept for years, so the market moves in life events: relocations, insurance changes, new families, and a steady stream of overdue patients. Competition is other practices' inertia more than their marketing. Search plus reviews is the whole funnel, and cosmetic offerings are the high-margin edge where paid ads actually change behavior.",
};

const SEASONALITY: Record<string, string> = {
  "Restaurants & cafés":
    "Expect lifts around holidays, Valentine's, Mother's Day, graduation season, and patio weather, with a January slump and late-summer softness. Push spend at the start of each lift — people plan occasions days ahead, not weeks — and use quiet stretches to promote weekday habits like lunch and coffee rather than going dark.",
  "Home services":
    "Demand tracks the weather and the calendar: HVAC spikes at the first heat wave and cold snap, exteriors and landscaping peak spring through summer, and interior work fills winter. Advertise a season early — the maintenance pitch lands cheapest right before the emergency season everyone else pays a premium to advertise in.",
  "Health & beauty":
    "Peaks come ahead of event seasons — weddings and proms in spring, holidays in November-December — plus a strong New Year self-improvement wave. Treatments with lead times (a series of sessions, visible-results windows) should be marketed 6-8 weeks before the moment people want results, and January is for memberships and maintenance plans.",
  "Fitness studios":
    "January is the giant wave, with secondary swells in early summer and September's back-to-routine reset; December and mid-summer are the troughs. Spend hardest in the first two weeks of a wave when intent is highest, and use troughs for community and retention stories that make the next wave's joiners feel they're joining something.",
  "Retail & boutiques":
    "Q4 holiday is the year's engine, with gift moments (Mother's Day, Valentine's, graduations) and seasonal wardrobe turns in between; January-February run quiet. Build audiences cheaply in the off-season with new-arrival and point-of-view content, then spend into the gift windows when purchase intent — and ad prices — peak.",
  "Auto services":
    "Peaks arrive with seasonal switchovers — pre-winter checks, first-snow tire rushes, summer road-trip prep — and potholes' spring aftermath. Maintenance demand is steadier than repair demand, so advertise inspection and prep offers just before each seasonal rush, and stay visible year-round for the breakdown searches that can't be timed.",
  "Dental & wellness":
    "Year-end brings a use-it-or-lose-it insurance rush and January brings resolution energy; back-to-school drives family checkups in August-September, and summer is the classic slow stretch. Cosmetic interest climbs before wedding and photo seasons — promote whitening and aligners in spring, and hygiene recalls when the calendar does the persuading.",
};

const FIRST_MOVE_BY_BAND: Record<string, string> = {
  "$": "Lead your first ad with your single best-value item and its real price — at your price point, the number itself is the hook.",
  "$$": "Lead your first ad with your most-ordered item, named with its price — specific and mid-market beats clever every time.",
  "$$$": "Lead your first ad with your signature offering and its standard, price stated plainly — the premium number filters for the right customer.",
};

function priceRange(services: Service[]): { low: number; high: number; count: number } | null {
  const prices = services
    .filter((s) => s.is_active && typeof s.price_cents === "number" && s.price_cents! > 0)
    .map((s) => s.price_cents! / 100)
    .sort((a, b) => a - b);
  if (prices.length === 0) return null;
  return { low: prices[0], high: prices[prices.length - 1], count: prices.length };
}

const fmt = (n: number) => `$${n % 1 === 0 ? n : n.toFixed(2)}`;

export function buildFallbackBrief(business: Business, services: Service[]): NewBusinessBrief {
  const active = services.filter((s) => s.is_active);
  const named = active.slice(0, 3).map((s) => s.name);
  const place = `${business.city}${business.region ? `, ${business.region}` : ""}`;
  const band = business.price_band ?? "$$";

  const doesWell: string[] = [];
  if (named.length > 0) {
    doesWell.push(
      `A focused menu people can actually choose from — ${named.join(", ")}${active.length > 3 ? ` and ${active.length - 3} more` : ""}.`,
    );
  }
  doesWell.push(
    `A real place in ${place} — local intent converts far better than broad reach, and you own the ${business.radius_miles}-mile radius that matters.`,
  );
  if (business.brand_voice_notes) {
    doesWell.push("A voice of your own — your ads can sound like you, not like a template.");
  }

  const advantages = [
    PRICE_ADVANTAGE[band] ?? PRICE_ADVANTAGE["$$"],
    "Speed: TRND hands you a finished campaign while competitors are still noticing the trend — first-mover on local demand is cheap attention.",
    "One clear offer per ad, priced from your actual menu — specificity beats cleverness in this category.",
  ];

  const watchouts = WATCHOUTS[business.category] ?? [
    "Don't compete on price alone — sell the thing only you can claim.",
    "One offer per ad; stacked offers depress conversion.",
  ];

  const bandWord = band === "$" ? "budget-friendly" : band === "$$$" ? "premium" : "mid-range";
  const positioning = [
    `${business.name} is the ${bandWord} ${business.category.toLowerCase().replace(/ & /g, " and ")} answer for people within ${business.radius_miles} miles of ${place}`,
    named.length > 0 ? ` — known for ${named[0].toLowerCase()}` : "",
    `. The idea your ads should repeat: one specific offer, from your real menu, for people close enough to act on it this week.`,
  ].join("");

  const range = priceRange(active);
  const pricingRead = range
    ? `Your listed prices run ${fmt(range.low)} to ${fmt(range.high)} across ${range.count} priced offering${range.count === 1 ? "" : "s"}, which reads as ${bandWord} for ${business.category.toLowerCase()}. ${
        band === "$$$"
          ? "State prices plainly — at the premium end, the number qualifies the customer before the click."
          : "Name the exact price in the ad — a real number outperforms 'affordable' in every local category."
      }`
    : `No prices are attached to your offerings yet — add them in Settings: ads that name a real number consistently beat vague claims, and TRND builds offers from your actual prices.`;

  const firstMoves = [
    active[0]
      ? `${FIRST_MOVE_BY_BAND[band] ?? FIRST_MOVE_BY_BAND["$$"]} For you that's likely ${active[0].name}${active[0].price_cents ? ` at ${fmt(active[0].price_cents / 100)}` : ""}.`
      : FIRST_MOVE_BY_BAND[band] ?? FIRST_MOVE_BY_BAND["$$"],
    `Point every ad at the ${business.radius_miles}-mile radius around ${business.city} — paying to reach people who can't visit is the most common local-ad money leak.`,
    `Record results after each campaign — TRND's recommendations sharpen with every real number you give it.`,
  ];

  // Watchlist without an LLM: the actual offerings, their "near me" intent
  // variants, and the category's full stock list — regenerated properly
  // (deeper, with lexicon and subreddits) once Gemini runs.
  const categoryConfig = CATEGORY_CONFIGS.find((c) => c.category === business.category);
  const seenTerms = new Set<string>();
  const watchTerms = [
    ...active.slice(0, 10).map((s) => s.name.toLowerCase()),
    ...active.slice(0, 5).map((s) => `${s.name.toLowerCase()} near me`),
    ...(categoryConfig?.watchTerms ?? []),
  ]
    .map((t) => t.trim())
    .filter((t) => t.length >= 3 && !seenTerms.has(t) && (seenTerms.add(t) || true))
    .slice(0, 20);

  // Classification vocabulary without an LLM: the category's stock lexicon
  // plus every substantive word in the owner's own service names.
  const seenWords = new Set<string>(categoryConfig?.lexicon ?? []);
  const lexicon = [
    ...(categoryConfig?.lexicon ?? []),
    ...active
      .flatMap((s) => s.name.toLowerCase().split(/[^a-z0-9]+/))
      .filter((w) => w.length > 3 && !seenWords.has(w) && (seenWords.add(w) || true)),
  ].slice(0, 24);

  return {
    business_id: business.id,
    positioning,
    customer_segments: SEGMENTS[business.category] ?? [
      "Nearby customers with immediate intent — they choose among whoever is visible and close when the need hits.",
      "Repeat customers whose only comparison is their last visit — consistency is what keeps them.",
    ],
    market_context:
      MARKET_CONTEXT[business.category] ??
      `Local ${business.category.toLowerCase()} is won inside the radius: visibility when nearby intent appears, and a reason to be chosen over the incumbent habit.`,
    pricing_read: pricingRead,
    seasonality:
      SEASONALITY[business.category] ??
      "Local demand follows the calendar — holidays, seasons, and paydays. Watch your own busiest weeks and advertise into the two weeks before them.",
    does_well: doesWell,
    moat: MOATS[business.category] ?? "Local trust, earned in person, that bigger players can't buy.",
    advantages,
    watchouts,
    first_moves: firstMoves,
    watch_terms: watchTerms,
    lexicon,
    subreddits: categoryConfig?.subreddits ?? [],
    model_used: BRIEF_FALLBACK_MODEL,
    prompt_version: BRIEF_PROMPT_VERSION,
  };
}

/**
 * Best-effort site text for the analysis when the caller doesn't already
 * have it (settings edits, lazy regeneration): one crawl of their site,
 * failures swallowed.
 */
async function fetchSiteTextForBrief(website: string | null): Promise<string | undefined> {
  if (!website) return undefined;
  try {
    const { fetchSiteCorpus, normalizeUrl } = await import("@/lib/import/website");
    const url = normalizeUrl(website);
    if (!url) return undefined;
    const corpus = await fetchSiteCorpus(url);
    return corpus.text || undefined;
  } catch (err) {
    console.warn("[ai] site fetch for brief failed (non-fatal):", (err as Error).message);
    return undefined;
  }
}

/** True while onboarding's own background generation is presumably still
 * writing this business's analysis — don't start a second one. */
export function briefLikelyInFlight(businessCreatedAt: string): boolean {
  return Date.now() - new Date(businessCreatedAt).getTime() < 5 * 60_000;
}

export async function generateBusinessBrief(
  business: Business,
  services: Service[],
  siteText?: string,
): Promise<NewBusinessBrief> {
  if (isGeminiConfigured) {
    try {
      const { generateBriefWithGemini } = await import("./gemini");
      const text = siteText ?? (await fetchSiteTextForBrief(business.website));
      return await generateBriefWithGemini(business, services, text);
    } catch (err) {
      console.warn("[ai] Gemini brief failed — using deterministic fallback:", (err as Error).message);
    }
  }
  return buildFallbackBrief(business, services);
}